name: Python CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ghas-github-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.2
    with:
      poetry-version: latest
      python-version: 3.12
